### ISSUE TITLE
Discussion on what's left to publish

### ISSUE THREAD

**Issue by kentcdodds** [hyrwork/glamorous-native#1]
Great work getting this going! Opening this to continue discussion from https://github.com/paypal/glamorous/issues/7

I'm going to bow out. @ mention me if you'd like my input! Thanks again. This is fantastic :clap:

**Comment by ssomnoremac** [comment]
great, thanks so much for the support @kentcdodds 

I think we can keep it to a short list to publish. Others feel free to add.

1. Handle animated components
2. Decide on a proper api to handle dynamic style rules (functions passed to factory)
3. Add proper README
